---
# vars file for deploy_app
wait_cancel: 5
dest_app_v1: /opt/linuxtips/app-v1.yml
dest_app_v2: /opt/linuxtips/app-v2.yml
number_replicas_old_version: 1
number_replicas_new_version: 10
old_version: 1.0.0
new_version: 2.0.0
prometheus_scrape: "true"
prometheus_port: 32111
nginx_port: 80
