- name: Copiando o Arquivo de Deploy do App V1
  template:
    src: app-v1.yml.j2
    dest: "{{ dest_app_v1 }}"
    owner: root
    group: root
    mode: 0644
  register: copy_deploy_app_v1

- name: Copiando o Arquivo de Deploy do App V2
  template:
    src: app-v2.yml.j2
    dest: "{{ dest_app_v2 }}"
    owner: root
    group: root
    mode: 0644
  register: copy_deploy_app_v2

- name: Deploy da App V2
  k8s:
    state: present
    namespace: default
    src: "{{ dest_app_v2 }}"

- name: Scale Down da App-v1
  k8s:
    state: present
    namespace: default
    src: "{{ dest_app_v1 }}"

- name: Tempo para pensar, caso ocorra algo errado, pressione crtl+c para cancelar
  pause:
    minutes: "{{ wait_cancel }}"

- name: Removendo o App-v1
  k8s:
    state: absent
    namespace: default
    src: "{{ dest_app_v1 }}"
